import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import Footer from "@/components/Footer/Footer";
import { Providers } from "@/redux/provider";
import SessionAuthProvider from "@/context/SessionAuthProvider";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server';


const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700","900"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const locale = await getLocale();
  
    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <NextIntlClientProvider messages={messages}>
              <SessionAuthProvider>
                  <Providers>
                    {children}
                    <Footer />
                  </Providers>
              </SessionAuthProvider>
          </NextIntlClientProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}