import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import StyledComponentsRegistry from "./StyledComponentsRegistry";
import Footer from "@/components/Footer/Footer";


const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700","900"], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <StyledComponentsRegistry>
          {children}
          <Footer/>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
